spring.application.name=EventsApp
logging.level.org.springframework.security=TRACE
#Google Login
spring.security.oauth2.client.registration.google.client-id=995116893557-50ticjb9vuq99680t6irm799p1ekq31m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#Database
spring.datasource.url=jdbc:postgresql://ep-steep-mountain-abi5wp0i-pooler.eu-west-2.aws.neon.tech/EventsDatabase?user=EventsDatabase_owner&password=npg_r5NcqwyKuEA0&sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.include=health
server.address=0.0.0.0
