spring.application.name=EventsApp
logging.level.org.springframework.security=TRACE
#Database
spring.datasource.url=jdbc:postgresql://ep-steep-mountain-abi5wp0i-pooler.eu-west-2.aws.neon.tech/EventsDatabase?user=EventsDatabase_owner&password=npg_r5NcqwyKuEA0&sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.include=health
server.address=0.0.0.0
